version: '3.4'

services:
  backend:
    image: backend-memuaro
    build:
      context: .\backend\MemuaroApp
      dockerfile: Dockerfile
    ports:
      - "5000:80"

  frontend:
    image: frontend-memuaro
    build:
      context: .\frontend
      dockerfile: Dockerfile
    ports:
      - "5001:4200"
