version: '3.7'

services:
  backend:
    image: backend-memuaro
    build:
      context: ./backend/RememoryApp
      dockerfile: Dockerfile
    ports:
      - "5000:80"

  frontend:
    image: frontend-memuaro
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
    volumes:
      - /etc/letsencrypt/live/rememory.ownchgk.ru/fullchain.pem:/etc/letsencrypt/live/rememory.ownchgk.ru/fullchain.pem
      - /etc/letsencrypt/live/rememory.ownchgk.ru/privkey.pem:/etc/letsencrypt/live/rememory.ownchgk.ru/privkey.pem
      - /etc/letsencrypt/options-ssl-nginx.conf:/etc/letsencrypt/options-ssl-nginx.conf
      - /etc/letsencrypt/ssl-dhparams.pem:/etc/letsencrypt/ssl-dhparams.pem
    ports:
      - "80:80"
      - "443:443"